Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

AllCops:
  # Include gemspec and Rakefile
  Include:
    - '**/*.gemspec'
    - '**/Rakefile'
  Exclude:
    - 'spec/**/*'
    - 'bin/**/*'
